### PR TITLE
[GH-94] Disable S3 settings if AWS config is invalid

### LINKED ISSUE #94: Invalid S3 bucket settings causes plugin to not start; must edit config to fix
When the connections settings for the S3 bucket are invalid, or the bucket cannot be reached, the plugin will refuse to start, and there is no way to get to the settings UI to fix.  You must manually edit the config to disable S3 to get the UI back.

If the S3 bucket connection fails on start-up we need to provide a way to remedy. My suggestion is, on startup, if S3 is enabled and the connection fails, disable S3 then exit plugin.

### PR DESCRIPTION
**Pull request by raghavaggarwal2308**
#### Summary
- Disable AWS settings if AWS config is invalid

#### How to test?
1. Enable S3 settings and add a invalid config
2. Save the config
3. Refresh the page, the S3 settings should be disabled.

#### Ticket Link
Fixes #94

### CODE REVIEW

File: server/plugin.go [hunk 1]
```diff
@@ -175,6 +175,17 @@ func (p *Plugin) Reconfigure() error {
 	}
 
 	if err = filesBackend.TestConnection(); err != nil {
+		pluginConfig := p.Client.Configuration.GetPluginConfig()
+
+		// Disable the S3 settings in case the AWS config is invalid
+		pluginConfig["amazons3bucketsettings"].(map[string]interface{})["Enable"] = false
```
Comment (wiggin77) [inline server/plugin.go:181]: @raghavaggarwal2308  Since the `fileBackend` remains the invalid S3 config, the plugin will still fail as it proceeds.  I think we need to re-fetch the settings and create another non-S3 backend here.

Comment (raghavaggarwal2308) [reply server/plugin.go:181]: @wiggin77 Since the AWS config is disabled. The filesbackend will update its value with the MM file storage config on line `163`. I have also tested this and its working fine. Please let me know your thoughts.

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by fmartingr — APPROVED** [review]

**Review by AayushChaudhary0001 — APPROVED** [review]
This PR has been tested and works fine if the S3 configs are entered invalid, the setting is changed to false. Looks good to me, approved.
