### PR TITLE
fix: check for enterprise licence on plugin activation

### LINKED ISSUE #5: Check for Enterprise License
The plugin should refuse to run if an Enterprise license is not present.

### PR DESCRIPTION
**Pull request by fmartingr**
Check for a valid enterprise licence on plugin activation.

Fixes #5

### CODE REVIEW

File: server/plugin.go [hunk 1]
```diff
@@ -56,6 +56,14 @@ type Plugin struct {
...
 
 func (p *Plugin) OnActivate() error {
+	// Check for an enterprise license or a development environment
+	config := p.API.GetConfig()
+	license := p.API.GetLicense()
+
+	if !pluginapi.IsEnterpriseLicensedOrDevelopment(config, license) {
+		return fmt.Errorf("this plugin requires an Enterprise license")
+	}
+
```
Comment (mickmister) [inline server/plugin.go:66]: Excellent :+1:

**Review by mickmister — APPROVED** [review]
